export type FieldType =
  | 'text'
  | 'number'
  | 'textarea'
  | 'date'
  | 'select'
  | 'multiselect'
  | 'password'
  | 'file';

export type ResourceField = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { label: string; value: string | number }[];
  optionsKey?: string;
  readKey?: string;
};

export type ResourceConfig = {
  key: string;
  title: string;
  endpoint: string;
  columns: { key: string; label: string; tooltip?: string }[];
  fields: ResourceField[];
  multipart?: boolean;
  readonly?: boolean;
  actionHeader?: string;
};

export const resources: ResourceConfig[] = [
  {
    key: 'items',
    title: 'Hardware',
    endpoint: '/items',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'label', label: 'Label' },
      { key: 'itemType', label: 'Hardware Type' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'model', label: 'Model' },
      { key: 'sn', label: 'Serial Number' },
      { key: 'purchasedate', label: 'Purchase Date' },
      { key: 'warrantyRemain', label: 'Warranty Remaining Days' },
      { key: 'ipv4', label: 'IPv4' },
      { key: 'dpt', label: 'Department' },
      { key: 'principal', label: 'Principal' },
      { key: 'status', label: 'Status' },
      { key: 'location', label: 'Location' },
      { key: 'rack', label: 'Rack' },
      { key: 'function', label: 'Function' },
      { key: 'software', label: 'Software' },
      { key: 'remadmip', label: 'Remote Management IP' },
      { key: 'tags', label: 'Tags' },
    ],
    fields: [
      { key: 'label', label: 'Label', type: 'text' },
      {
        key: 'itemTypeId',
        readKey: 'itemtypeid',
        label: 'Hardware Type',
        type: 'select',
        required: true,
        optionsKey: 'itemtypes',
      },
      { key: 'isPart', readKey: 'ispart', label: 'Sub-component', type: 'number', required: true },
      {
        key: 'rackMountable',
        readKey: 'rackmountable',
        label: 'Rack-mounted',
        type: 'number',
        required: true,
      },
      {
        key: 'manufacturerId',
        readKey: 'manufacturerid',
        label: 'Manufacturer',
        type: 'select',
        required: true,
        optionsKey: 'agents',
      },
      { key: 'model', label: 'Model', type: 'text', required: true },
      { key: 'uSize', readKey: 'usize', label: 'Size (U)', type: 'number' },
      { key: 'sn', label: 'Serial Number', type: 'text' },
      { key: 'sn2', label: 'Serial Number 2', type: 'text' },
      { key: 'sn3', label: 'Service Tag', type: 'text' },
      { key: 'comments', label: 'Comments', type: 'textarea' },
      { key: 'principal', label: 'Principal', type: 'text', required: true },
      {
        key: 'status',
        readKey: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        optionsKey: 'statustypes',
      },
      {
        key: 'dptId',
        readKey: 'dptid',
        label: 'Department',
        type: 'select',
        optionsKey: 'dpttypes',
      },
      {
        key: 'locationId',
        readKey: 'locationid',
        label: 'Location',
        type: 'select',
        optionsKey: 'locations',
      },
      {
        key: 'locAreaId',
        readKey: 'locareaid',
        label: 'Area/Room',
        type: 'select',
        optionsKey: 'locareas',
      },
      { key: 'rackId', readKey: 'rackid', label: 'Rack', type: 'select', optionsKey: 'racks' },
      { key: 'rackPosition', readKey: 'rackposition', label: 'Rack Position', type: 'number' },
      {
        key: 'rackPosDepth',
        readKey: 'rackposdepth',
        label: 'Rack Depth Position',
        type: 'number',
      },
      { key: 'function', label: 'Function', type: 'text' },
      { key: 'userId', readKey: 'userid', label: 'User', type: 'select', optionsKey: 'users' },
      { key: 'purchaseDate', readKey: 'purchasedate', label: 'Purchase Date', type: 'date' },
      {
        key: 'warrantyMonths',
        readKey: 'warrantymonths',
        label: 'Warranty Months',
        type: 'number',
      },
      { key: 'warrInfo', readKey: 'warrinfo', label: 'Warranty Information', type: 'textarea' },
      {
        key: 'maintenanceInfo',
        readKey: 'maintenanceinfo',
        label: 'Maintenance Records',
        type: 'textarea',
      },
      { key: 'hd', label: 'Hard Drive', type: 'text' },
      { key: 'ram', label: 'Memory', type: 'text' },
      { key: 'cpu', label: 'CPU Model', type: 'text' },
      { key: 'cpuNo', readKey: 'cpuno', label: 'CPU Count', type: 'text' },
      { key: 'coresPerCpu', readKey: 'corespercpu', label: 'Cores per CPU', type: 'text' },
      { key: 'raid', label: 'Raid Card Model', type: 'text' },
      { key: 'raidConfig', readKey: 'raidconfig', label: 'Raid Configuration', type: 'textarea' },
      { key: 'macs', label: 'MAC Addresses', type: 'text' },
      { key: 'ipv4', label: 'IPv4', type: 'text' },
      { key: 'ipv6', label: 'IPv6', type: 'text' },
      { key: 'remAdmIp', readKey: 'remadmip', label: 'Remote Management IP', type: 'text' },
      { key: 'dnsName', readKey: 'dnsname', label: 'Management Cable', type: 'text' },
      { key: 'panelPort', readKey: 'panelport', label: 'Bond Name', type: 'text' },
      {
        key: 'switchId',
        readKey: 'switchid',
        label: 'Switch',
        type: 'select',
        optionsKey: 'items_ref',
      },
      { key: 'switchPort', readKey: 'switchport', label: 'Business Cable', type: 'text' },
      { key: 'ports', label: 'Network Ports', type: 'text' },
      { key: 'purchPrice', readKey: 'purchprice', label: 'Purchase Price (￥)', type: 'text' },
      { key: 'origin', label: 'Supplier', type: 'text' },
      {
        key: 'itemLinks',
        label: 'Internal Hardware Links',
        type: 'multiselect',
        optionsKey: 'items_ref',
      },
      {
        key: 'invoiceLinks',
        label: 'Related Documents',
        type: 'multiselect',
        optionsKey: 'invoices_ref',
      },
      {
        key: 'softwareLinks',
        label: 'Related Software',
        type: 'multiselect',
        optionsKey: 'software_ref',
      },
      {
        key: 'contractLinks',
        label: 'Related Contracts',
        type: 'multiselect',
        optionsKey: 'contracts_ref',
      },
      { key: 'fileLinks', label: 'Related Files', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'software',
    title: 'Software',
    endpoint: '/software',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'title', label: 'Title' },
      { key: 'version', label: 'Version' },
      { key: 'purchdate', label: 'Purchase Date' },
      { key: 'maintend', label: 'Maintenance End', tooltip: 'Maintenance Expiration Date' },
      { key: 'slicenseinfo', label: 'License Information' },
      { key: 'sinfo', label: 'Additional Information' },
      { key: 'tags', label: 'Tags' },
      { key: 'qty', label: 'Quantity' },
      { key: 'vendor', label: 'Vendor', tooltip: 'Obtained from related documents' },
      { key: 'invoice', label: 'Document' },
      { key: 'installedon', label: 'Installed On' },
    ],
    fields: [
      { key: 'title', readKey: 'stitle', label: 'Title', type: 'text', required: true },
      { key: 'version', readKey: 'sversion', label: 'Version', type: 'text', required: true },
      {
        key: 'manufacturerId',
        readKey: 'manufacturerid',
        label: 'Manufacturer',
        type: 'select',
        required: true,
        optionsKey: 'agents',
      },
      { key: 'purchaseDate', readKey: 'purchdate', label: 'Purchase Date', type: 'date' },
      { key: 'licenseQty', readKey: 'licqty', label: 'License Quantity', type: 'number' },
      {
        key: 'licenseType',
        readKey: 'lictype',
        label: 'License Type',
        type: 'select',
        options: [
          { label: 'Per Device', value: 0 },
          { label: 'Per CPU', value: 1 },
          { label: 'Per Core', value: 2 },
        ],
      },
      {
        key: 'slicenseInfo',
        readKey: 'slicenseinfo',
        label: 'License Information',
        type: 'textarea',
      },
      { key: 'info', readKey: 'sinfo', label: 'Additional Information', type: 'textarea' },
      { key: 'itemLinks', label: 'Related Hardware', type: 'multiselect', optionsKey: 'items_ref' },
      {
        key: 'invoiceLinks',
        label: 'Related Invoices',
        type: 'multiselect',
        optionsKey: 'invoices_ref',
      },
      {
        key: 'contractLinks',
        label: 'Related Contracts',
        type: 'multiselect',
        optionsKey: 'contracts_ref',
      },
      { key: 'fileLinks', label: 'Related Files', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'invoices',
    title: 'Invoices',
    endpoint: '/invoices',
    actionHeader: 'Action',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'vendor', label: 'Vendor' },
      { key: 'buyer', label: 'Buyer' },
      { key: 'date', label: 'Date' },
      { key: 'number', label: 'Order Number' },
      { key: 'description', label: 'Description' },
      { key: 'files', label: 'Related Files' },
    ],
    fields: [
      { key: 'number', label: 'Order Number', type: 'text', required: true },
      {
        key: 'vendorId',
        readKey: 'vendorid',
        label: 'Vendor',
        type: 'select',
        required: true,
        optionsKey: 'agents',
      },
      {
        key: 'buyerId',
        readKey: 'buyerid',
        label: 'Buyer',
        type: 'select',
        required: true,
        optionsKey: 'agents',
      },
      { key: 'date', readKey: 'date', label: 'Date', type: 'date', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'itemLinks', label: 'Related Hardware', type: 'multiselect', optionsKey: 'items_ref' },
      {
        key: 'softwareLinks',
        label: 'Related Software',
        type: 'multiselect',
        optionsKey: 'software_ref',
      },
      {
        key: 'contractLinks',
        label: 'Related Contracts',
        type: 'multiselect',
        optionsKey: 'contracts_ref',
      },
      { key: 'fileLinks', label: 'Related Files', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'agents',
    title: 'Agents',
    endpoint: '/agents',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'type', label: 'Type' },
      { key: 'title', label: 'Name' },
      { key: 'contactinfo', label: 'Contract Information' },
      { key: 'contacts', label: 'Contracts' },
    ],
    fields: [
      { key: 'title', label: 'Name', type: 'text', required: true },
      {
        key: 'types',
        readKey: 'type',
        label: 'Type',
        type: 'multiselect',
        options: [
          { label: 'Vendor', value: 4 },
          { label: 'Software Vendor', value: 2 },
          { label: 'Hardware Vendor', value: 8 },
          { label: 'Buyer', value: 1 },
          { label: 'Contractor', value: 16 },
        ],
      },
      {
        key: 'contactInfo',
        readKey: 'contactinfo',
        label: 'Contact Information',
        type: 'textarea',
      },
    ],
  },
  {
    key: 'files',
    title: 'Files',
    endpoint: '/files',
    multipart: true,
    actionHeader: 'Action',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'typedesc', label: 'Type' },
      { key: 'title', label: 'Title' },
      { key: 'fname', label: 'File' },
      { key: 'links', label: 'Links' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      {
        key: 'typeId',
        readKey: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        optionsKey: 'filetypes',
      },
      { key: 'date', readKey: 'date', label: 'Date', type: 'date', required: true },
      { key: 'file', label: 'File', type: 'file' },
      {
        key: 'itemLinks',
        label: 'Associated hardware',
        type: 'multiselect',
        optionsKey: 'items_ref',
      },
      {
        key: 'softwareLinks',
        label: 'Associated software',
        type: 'multiselect',
        optionsKey: 'software_ref',
      },
      {
        key: 'invoiceLinks',
        label: 'Associated invoices',
        type: 'multiselect',
        optionsKey: 'invoices_ref',
      },
      { key: 'fileLinks', label: 'Associated files', type: 'multiselect', optionsKey: 'files_ref' },
      {
        key: 'contractLinks',
        label: 'Associated contracts',
        type: 'multiselect',
        optionsKey: 'contracts_ref',
      },
    ],
  },
  {
    key: 'contracts',
    title: 'Contracts',
    endpoint: '/contracts',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'parentid', label: 'Parent ID' },
      { key: 'type', label: 'Type' },
      { key: 'number', label: 'Number' },
      { key: 'title', label: 'Title' },
      { key: 'startdate', label: 'Start Date' },
      { key: 'currentenddate', label: 'End Date' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'number', label: 'Number', type: 'text', required: true },
      {
        key: 'typeId',
        readKey: 'type',
        label: 'Contract Type',
        type: 'select',
        required: true,
        optionsKey: 'contracttypes',
      },
      {
        key: 'subTypeId',
        readKey: 'subtype',
        label: 'Contract Subtype',
        type: 'select',
        optionsKey: 'contractsubtypes',
      },
      {
        key: 'parentId',
        readKey: 'parentid',
        label: 'Parent Contract',
        type: 'select',
        optionsKey: 'contracts_ref',
      },
      {
        key: 'contractorId',
        readKey: 'contractorid',
        label: 'Contractor',
        type: 'select',
        required: true,
        optionsKey: 'agents',
      },
      { key: 'startDate', readKey: 'startdate', label: 'Start Date', type: 'date', required: true },
      {
        key: 'currentEndDate',
        readKey: 'currentenddate',
        label: 'End Date',
        type: 'date',
        required: true,
      },
      { key: 'renewals', label: 'Renewal Information', type: 'text' },
      { key: 'totalCost', readKey: 'totalcost', label: 'Total Cost', type: 'text' },
      { key: 'description', label: 'Contract Description', type: 'textarea' },
      { key: 'comments', label: 'Comments', type: 'textarea' },
      {
        key: 'itemLinks',
        label: 'Associated Hardware',
        type: 'multiselect',
        optionsKey: 'items_ref',
      },
      {
        key: 'softwareLinks',
        label: 'Associated Software',
        type: 'multiselect',
        optionsKey: 'software_ref',
      },
      {
        key: 'invoiceLinks',
        label: 'Associated Invoices',
        type: 'multiselect',
        optionsKey: 'invoices_ref',
      },
      { key: 'fileLinks', label: 'Associated Files', type: 'multiselect', optionsKey: 'files_ref' },
    ],
  },
  {
    key: 'locations',
    title: 'Locations',
    endpoint: '/locations',
    multipart: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Location Name/Building Name' },
      { key: 'floor', label: 'Floor' },
      { key: 'areaname', label: 'Area/Office' },
      { key: 'floorplanfn', label: 'Building Plan' },
    ],
    fields: [
      { key: 'name', label: 'Location Name', type: 'text', required: true },
      { key: 'floor', label: 'Floor', type: 'text', required: true },
      { key: 'file', label: 'Building Plan', type: 'file' },
    ],
  },
  {
    key: 'users',
    title: 'Users',
    endpoint: '/users',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'username', label: 'Username' },
      { key: 'userdesc', label: 'User Description' },
      { key: 'usertype', label: 'Type' },
      { key: 'itemCount', label: 'Hardware' },
    ],
    fields: [
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', readKey: 'pass', label: 'Password', type: 'password' },
      { key: 'userDesc', readKey: 'userdesc', label: 'User Description', type: 'text' },
      {
        key: 'userType',
        readKey: 'usertype',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'Full Access', value: 0 },
          { label: 'Read Only', value: 1 },
        ],
      },
    ],
  },
  {
    key: 'racks',
    title: 'Racks',
    endpoint: '/racks',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'occupation', label: 'In Use' },
      {
        key: 'population',
        label: 'Hardware',
        tooltip: 'How much hardware is assigned to this rack',
      },
      { key: 'usize', label: 'Height(U)*' },
      { key: 'depth', label: 'Depth' },
      { key: 'location', label: 'Location' },
      { key: 'area', label: 'Area/Room' },
      { key: 'label', label: 'Label' },
    ],
    fields: [
      { key: 'label', label: 'Label', type: 'text', required: true },
      {
        key: 'locationId',
        readKey: 'locationid',
        label: 'Location',
        type: 'select',
        required: true,
        optionsKey: 'locations',
      },
      {
        key: 'locAreaId',
        readKey: 'locareaid',
        label: 'Area',
        type: 'select',
        optionsKey: 'locareas',
      },
      { key: 'uSize', readKey: 'usize', label: 'Height(U)*', type: 'number', required: true },
      { key: 'depth', label: 'Depth(mm)', type: 'number', required: true },
      { key: 'model', label: 'Model', type: 'text' },
      {
        key: 'revNums',
        readKey: 'revnums',
        label: 'Revision Numbers',
        type: 'select',
        options: [
          { value: 0, label: '1=Bottom' },
          { value: 1, label: '1=Top' },
        ],
      },
      { key: 'comments', label: 'Comments', type: 'textarea' },
    ],
  },
];

export const resourceMap = Object.fromEntries(resources.map(r => [r.key, r])) as Record<
  string,
  ResourceConfig
>;
